spring:
  profiles:
    active: local
  application:
    name: kong-ai-code
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kong_ai_code
    username: root
    password: kong0305
    # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  session:
    store-type: redis
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jaychou.kongaicode.controller
# knife
knife4j:
  enable: true
  setting:
    language: zh_cn

